[package]
name = "rnet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"

num-format = "0.4.0"

ndarray = "0.15.0"
ndarray-rand = "0.14.0"
